#!/usr/bin/env python3
"""
CENG381 - PDF generator for folders 2026-05-21 + 2026-06-04 + last/
Topics: Martingales | Optional Stopping Theorem | Wald's Equality | De Moivre's Martingale
"""
import os
from fpdf import FPDF

BASE = "/Users/apple/Desktop/CENG381"
QQ   = os.path.join(BASE, "Generated_Questions")
AK   = os.path.join(BASE, "Answer_Keys")

# ── PDF helper ────────────────────────────────────────────────────────────────
class ExamPDF(FPDF):
    def __init__(self, sub=""):
        super().__init__()
        self._sub = sub
        self.set_auto_page_break(True, margin=20)
        self.set_margins(25, 25, 25)

    def header(self):
        self.set_font("Helvetica", "B", 12)
        self.cell(0, 8, "CENG381 Stochastic Processes", align="C",
                  new_x="LMARGIN", new_y="NEXT")
        self.set_font("Helvetica", "", 10)
        self.cell(0, 6, self._sub, align="C", new_x="LMARGIN", new_y="NEXT")
        self.ln(3)
        self.line(self.l_margin, self.get_y(), self.w - self.r_margin, self.get_y())
        self.ln(5)

    def footer(self):
        self.set_y(-15)
        self.set_font("Helvetica", "I", 8)
        self.cell(0, 10, f"Page {self.page_no()}", align="C")

    def Q(self, n, pts, text):
        self.set_font("Helvetica", "B", 11)
        self.multi_cell(0, 7, f"Q{n} ({pts} points).  {text}")
        self.ln(1)

    def sub(self, label, text):
        self.set_font("Helvetica", "", 10.5)
        x0 = self.l_margin + 10
        self.set_x(x0)
        self.multi_cell(self.w - self.r_margin - x0, 6.5, f"{label})  {text}")
        self.ln(1)

    def txt(self, text, indent=0):
        self.set_font("Helvetica", "", 10.5)
        xi = self.l_margin + indent
        self.set_x(xi)
        self.multi_cell(self.w - self.r_margin - xi, 6.5, text)
        self.ln(1)

    def mat(self, lines):
        self.set_font("Courier", "", 10)
        for line in lines:
            self.set_x(self.l_margin + 20)
            self.cell(0, 5.8, line, new_x="LMARGIN", new_y="NEXT")
        self.ln(3)

    def defn(self, term, meaning):
        self.set_font("Helvetica", "B", 10.5)
        self.set_x(self.l_margin + 5)
        self.cell(60, 6.5, term)
        self.set_font("Helvetica", "", 10.5)
        self.multi_cell(0, 6.5, meaning)
        self.ln(0.5)

    def note(self, text):
        self.set_font("Helvetica", "I", 10)
        self.set_x(self.l_margin + 5)
        self.multi_cell(0, 6, text)
        self.ln(2)

    def sep(self):
        self.ln(3)
        self.set_draw_color(160, 160, 160)
        self.line(self.l_margin, self.get_y(), self.w - self.r_margin, self.get_y())
        self.set_draw_color(0)
        self.ln(5)

    def AL(self, text):
        self.set_font("Helvetica", "BU", 10.5)
        self.cell(0, 7, text, new_x="LMARGIN", new_y="NEXT")
        self.set_font("Helvetica", "", 10.5)
        self.ln(1)

    def AH(self, text):
        self.set_font("Helvetica", "B", 11)
        self.multi_cell(0, 7, text)
        self.ln(1)

    def save(self, path):
        os.makedirs(os.path.dirname(path), exist_ok=True)
        self.output(path)
        print(f"  Saved -> {os.path.relpath(path, BASE)}")


def qp(s, f): return os.path.join(QQ, s, f)
def ap(s, f): return os.path.join(AK, s, f)


# ==============================================================================
# 1.  MARTINGALES AND THE OPTIONAL STOPPING THEOREM
# ==============================================================================

def martin_ost_q():
    S = "Martingales_and_Optional_Stopping"
    p = ExamPDF("Martingales and the Optional Stopping Theorem  -  Question Set 1")
    p.add_page()

    p.txt("Notation used in this question set:")
    p.defn("Filtration F_n:",
           "F_n represents all information available up to and including time n. "
           "Formally it is the sigma-algebra generated by X_1, ..., X_n.")
    p.defn("Martingale M(n):",
           "a stochastic process adapted to F_n such that E[|M(n)|] < inf and "
           "E[M(n+1) | F_n] = M(n)  for all n >= 0. "
           "The conditional expected future value always equals the present value "
           "(a 'fair game').")
    p.defn("Supermartingale:",
           "E[M(n+1) | F_n] <= M(n)  (expected value non-increasing -- 'unfair game').")
    p.defn("Submartingale:",
           "E[M(n+1) | F_n] >= M(n)  (expected value non-decreasing).")
    p.defn("Stopping time T:",
           "a random variable T taking values in {0,1,2,...,inf} such that the event "
           "{T = n} depends only on F_n (i.e. you can tell whether to stop at time n "
           "using only information available by time n).")
    p.defn("Optional Stopping Thm:",
           "If M(n) is a martingale and T is a stopping time satisfying either "
           "(i) T is bounded (T <= N for some fixed N), or "
           "(ii) E[T] < inf and |M(n+1)-M(n)| <= C for some constant C, "
           "then  E[M(T)] = E[M(0)].")
    p.note("OST says: the expected value at a stopping time equals the initial value. "
           "You cannot gain an advantage over a fair game by clever stopping.")
    p.ln(1)

    # ── Q1 ──
    p.Q(1, 30,
        "Let X_1, X_2, ... be i.i.d. with P(X_i = +1) = P(X_i = -1) = 1/2 "
        "(symmetric random walk steps). Define S(n) = X_1 + X_2 + ... + X_n "
        "with S(0) = 0.")
    p.sub("a",
          "Show that S(n) is a martingale by verifying "
          "E[S(n+1) | F_n] = S(n). "
          "Use the fact that X_{n+1} is independent of F_n and has E[X_{n+1}] = 0.")
    p.sub("b",
          "Define M(n) = S(n)^2 - n. Show M(n) is also a martingale. "
          "(Hint: write S(n+1)^2 = (S(n) + X_{n+1})^2, expand, take conditional "
          "expectation, and use E[X_{n+1}^2] = 1 and E[X_{n+1}] = 0.)")
    p.sub("c",
          "Now suppose X_i has E[X_i] = c > 0 (a biased walk drifting upward). "
          "Without computing, state whether S(n) is a martingale, supermartingale, "
          "or submartingale. What about -S(n)? Justify briefly.")

    p.sep()

    # ── Q2 ──
    p.Q(2, 35,
        "A gambler plays a symmetric random walk starting at position k, "
        "with absorbing barriers at 0 (ruin) and N (goal). "
        "Let T = first time S(n) reaches 0 or N. "
        "Assume E[T] < inf (it can be shown that T is always finite a.s.).")
    p.sub("a",
          "Apply the Optional Stopping Theorem to the martingale S(n) "
          "to find h(k) = P(reach N before 0 | S(0) = k). "
          "Use: E[S(T)] = E[S(0)] = k, and S(T) = N with probability h(k) "
          "or S(T) = 0 with probability 1-h(k).")
    p.sub("b",
          "Apply the Optional Stopping Theorem to the martingale M(n) = S(n)^2 - n "
          "to find E[T | S(0) = k], the expected number of steps to absorption. "
          "Use: E[M(T)] = E[M(0)] = k^2, and S(T)^2 = N^2 with prob h(k) "
          "or S(T)^2 = 0 with prob 1-h(k). Express E[T] in terms of k, N.")
    p.sub("c",
          "For N = 4 and k = 1, compute h(1) and E[T | S(0)=1]. "
          "Interpret: starting one step from ruin and three steps from the goal, "
          "how likely is the gambler to succeed, and how long does the game last?")

    p.sep()

    # ── Q3 ──
    p.Q(3, 35,
        "Consider the 'Stop When You're Ahead' strategy: a player bets on a "
        "fair coin repeatedly. Let S(n) = total winnings after n bets. "
        "The player uses stopping time T* = min{n >= 1 : S(n) > 0}, "
        "i.e. they stop as soon as they are ahead.")
    p.sub("a",
          "Is T* a valid stopping time? Explain why the event {T* = n} is "
          "determined by the outcomes X_1, ..., X_n only.")
    p.sub("b",
          "What is S(T*) whenever T* < inf? (That is, what are the possible "
          "values of S at the moment of stopping?) Since steps are +/-1, "
          "what is the only possible value of S(n) at the first positive time?")
    p.sub("c",
          "Despite S(n) being a martingale and T* being a stopping time, "
          "we have E[S(T*)] = 1 != 0 = S(0). Which condition of the OST fails? "
          "Show that E[T*] = inf for the symmetric random walk "
          "(by arguing that a symmetric random walk is recurrent and "
          "the expected return time to any state is infinite).")
    p.save(qp(S, "Question_Set_1.pdf"))


def martin_ost_a():
    S = "Martingales_and_Optional_Stopping"
    p = ExamPDF("Martingales and Optional Stopping Theorem  -  Answer Key 1")
    p.add_page()

    # ── Q1 ──
    p.AH("Q1  Solution")
    p.AL("a)  S(n) is a martingale:")
    p.txt("E[S(n+1) | F_n] = E[S(n) + X_{n+1} | F_n]\n"
          "                = E[S(n) | F_n] + E[X_{n+1} | F_n]\n"
          "                = S(n) + E[X_{n+1}]    (S(n) is F_n-measurable;\n"
          "                                         X_{n+1} is independent of F_n)\n"
          "                = S(n) + 0\n"
          "                = S(n)  (OK)\n\n"
          "So S(n) satisfies E[S(n+1)|F_n] = S(n): it is a martingale.")

    p.AL("b)  M(n) = S(n)^2 - n is a martingale:")
    p.txt("Compute E[M(n+1) | F_n]:\n\n"
          "  E[S(n+1)^2 - (n+1) | F_n]\n"
          "= E[(S(n) + X_{n+1})^2 | F_n] - (n+1)\n"
          "= E[S(n)^2 + 2*S(n)*X_{n+1} + X_{n+1}^2 | F_n] - (n+1)\n"
          "= S(n)^2 + 2*S(n)*E[X_{n+1}] + E[X_{n+1}^2] - (n+1)\n"
          "  [using S(n) is F_n-measurable, X_{n+1} independent of F_n]\n"
          "= S(n)^2 + 2*S(n)*0 + 1 - (n+1)\n"
          "= S(n)^2 - n\n"
          "= M(n)  (OK)\n\n"
          "So M(n) = S(n)^2 - n is a martingale.")

    p.AL("c)  Classification when E[X_i] = c > 0:")
    p.txt("E[S(n+1) | F_n] = S(n) + E[X_{n+1}] = S(n) + c > S(n).\n\n"
          "Since expected future value EXCEEDS current value, S(n) is a SUBMARTINGALE.\n"
          "(The walk has upward drift -- on average it grows.)\n\n"
          "For -S(n): E[-S(n+1) | F_n] = -S(n) - c < -S(n).\n"
          "So -S(n) is a SUPERMARTINGALE.\n"
          "(Flipping the sign reverses the inequality.)")

    p.sep()

    # ── Q2 ──
    p.AH("Q2  Solution")
    p.AL("a)  Winning probability h(k) = P(reach N before 0):")
    p.txt("Apply OST to the martingale S(n). Since T is bounded (T <= N^2 can\n"
          "be shown), the conditions are satisfied:\n\n"
          "  E[S(T)] = E[S(0)] = k\n\n"
          "At stopping time T, S(T) = N (with probability h(k)) or S(T) = 0\n"
          "(with probability 1 - h(k)). So:\n\n"
          "  E[S(T)] = N * h(k) + 0 * (1 - h(k)) = N * h(k)\n\n"
          "Setting equal:\n"
          "  N * h(k) = k\n"
          "  h(k) = k / N\n\n"
          "The probability of reaching N before 0 is exactly k/N -- proportional\n"
          "to the starting position. This is the classic Gambler's Ruin result\n"
          "for a symmetric random walk.")

    p.AL("b)  Expected absorption time E[T | S(0) = k]:")
    p.txt("Apply OST to the martingale M(n) = S(n)^2 - n:\n\n"
          "  E[M(T)] = E[M(0)] = k^2 - 0 = k^2\n\n"
          "At time T:\n"
          "  M(T) = S(T)^2 - T\n\n"
          "  E[M(T)] = E[S(T)^2] - E[T]\n"
          "           = [N^2 * h(k) + 0^2 * (1-h(k))] - E[T]\n"
          "           = N^2 * (k/N) - E[T]\n"
          "           = N*k - E[T]\n\n"
          "Setting equal to k^2:\n"
          "  N*k - E[T] = k^2\n"
          "  E[T] = N*k - k^2 = k*(N - k)")

    p.AL("c)  Numerical answer for N=4, k=1:")
    p.txt("  h(1) = 1/N = 1/4 = 0.25\n\n"
          "There is only a 25% chance of reaching the goal (N=4)\n"
          "before going broke, starting just one step away from ruin.\n\n"
          "  E[T] = k*(N-k) = 1*(4-1) = 3 steps\n\n"
          "The game lasts an average of 3 steps. This seems short, but makes\n"
          "sense: 75% of the time the gambler goes broke quickly (loses in 1 step\n"
          "with prob 1/2, or in a few steps), and only 25% of the time does the\n"
          "game last long enough to reach 4.")

    p.sep()

    # ── Q3 ──
    p.AH("Q3  Solution")
    p.AL("a)  T* is a valid stopping time:")
    p.txt("T* = min{n >= 1 : S(n) > 0}.\n\n"
          "The event {T* = n} means:\n"
          "  S(1) <= 0, S(2) <= 0, ..., S(n-1) <= 0, S(n) > 0.\n\n"
          "Each of these conditions depends only on X_1, ..., X_n (not on future\n"
          "steps), so {T* = n} is determined by F_n. Therefore T* is a valid\n"
          "stopping time: the decision to stop is based only on past outcomes.")

    p.AL("b)  Value of S at stopping:")
    p.txt("Each step X_i is either +1 or -1. So S(n) always changes by exactly 1\n"
          "at each step. The first time S(n) becomes positive (> 0), starting from\n"
          "S(0) = 0, the walk must reach +1 (it cannot jump from 0 or below to +2\n"
          "or higher in a single step of size +1).\n\n"
          "Therefore: S(T*) = +1 whenever T* < inf.\n\n"
          "The gambler always stops exactly 1 unit ahead when they stop.")

    p.AL("c)  Which OST condition fails? E[T*] = infinity:")
    p.txt("We have E[S(T*)] = 1 (since S(T*)=1 always when finite), but E[S(0)]=0.\n"
          "This contradicts OST unless one of its conditions fails.\n\n"
          "Condition (ii) requires E[T*] < inf with bounded increments.\n"
          "Increments are bounded (|X_i| = 1), so the issue must be E[T*] = inf.\n\n"
          "Why E[T*] = inf for symmetric random walk:\n"
          "  The symmetric random walk on Z is RECURRENT: it visits every integer\n"
          "  infinitely often with probability 1. In particular, it returns to 0\n"
          "  infinitely often.\n\n"
          "  The expected return time to state 0 for a symmetric random walk is\n"
          "  INFINITE (the walk is null-recurrent). Since T* is related to the\n"
          "  return time, E[T*] = inf.\n\n"
          "Conclusion: OST does NOT apply here because E[T*] = inf.\n"
          "The 'Stop When You're Ahead' strategy beats the fair game in expectation\n"
          "of the final amount -- but only by waiting an infinitely long time on\n"
          "average. No practical advantage exists.")
    p.save(ap(S, "Question_Set_1_Answers.pdf"))


# ==============================================================================
# 2.  WALD'S EQUALITY AND DE MOIVRE'S MARTINGALE
# ==============================================================================

def wald_demoivre_q():
    S = "Walds_Equality_and_De_Moivre_Martingale"
    p = ExamPDF("Wald's Equality and De Moivre's Martingale  -  Question Set 1")
    p.add_page()

    p.txt("Notation used in this question set:")
    p.defn("Wald's Equality:",
           "Let X_1, X_2, ... be i.i.d. with E[X] = mu. "
           "Let T be a stopping time with E[T] < inf, independent of future X_i. "
           "Then  E[S(T)] = mu * E[T],  where S(T) = X_1 + X_2 + ... + X_T.")
    p.defn("Second Wald Identity:",
           "If additionally E[X] = 0 and Var[X] = sigma^2, then "
           "E[S(T)^2] = sigma^2 * E[T].  "
           "(Equivalently, S(n)^2 - sigma^2*n is a martingale.)")
    p.defn("Biased random walk:",
           "Steps X_i are +1 with probability p and -1 with probability q = 1-p, "
           "where p != 1/2. The walk has drift E[X] = p - q = 2p - 1.")
    p.defn("De Moivre's martingale:",
           "For a biased walk with ratio r = q/p, the process M(n) = r^{S(n)} "
           "is a martingale. This is verified by showing E[r^{X_{n+1}}] = 1, "
           "which gives E[M(n+1) | F_n] = M(n) * E[r^{X_{n+1}}] = M(n).")
    p.defn("Jensen's Inequality:",
           "For a CONVEX function f and a random variable X with E[|X|] < inf, "
           "f(E[X]) <= E[f(X)].  "
           "Convex means the function curves upward: f''(x) >= 0 for all x. "
           "Examples: f(x) = x^2, f(x) = e^x, f(x) = r^x for r > 1.")
    p.note("De Moivre's martingale gives the Gambler's Ruin probability for the "
           "biased walk: apply OST to r^{S(n)} with absorbing barriers at 0 and N "
           "to get  P(reach N | start k) = (1 - r^k) / (1 - r^N)  when r = q/p != 1.")
    p.ln(1)

    # ── Q1 ──
    p.Q(1, 30,
        "You roll a fair die repeatedly. Let X_i be the outcome of roll i "
        "(X_i in {1,2,3,4,5,6}, each equally likely). Define S(n) = X_1+...+X_n "
        "and let T = min{n : S(n) >= 100} (stop as soon as the sum reaches 100).")
    p.sub("a",
          "Compute E[X_i] and Var[X_i] for a fair die. "
          "(Recall: E[X] = (1+2+...+6)/6  and  E[X^2] = (1^2+...+6^2)/6.)")
    p.sub("b",
          "Use Wald's Equality E[S(T)] = E[X] * E[T] to estimate E[T]. "
          "Note that when the walk hits 100 it may overshoot slightly "
          "(S(T) >= 100 but S(T-1) < 100), so S(T) ~ 100 approximately. "
          "Give the approximate value of E[T].")
    p.sub("c",
          "A casino game pays out $1 if the player reaches exactly sum = 100 "
          "with their rolls, and $0 otherwise. Would you expect this to be a "
          "common or rare event? "
          "Using the fact that the probability of hitting exactly 100 (rather than "
          "overshooting) is approximately 1/E[X] = 2/7 by the renewal theory result, "
          "what is the approximate probability of landing on exactly 100?")

    p.sep()

    # ── Q2 ──
    p.Q(2, 35,
        "A biased random walk has P(X_i = +1) = p = 3/5 and "
        "P(X_i = -1) = q = 2/5. The walk starts at position k = 2 "
        "with absorbing barriers at 0 (ruin) and N = 6 (goal).")
    p.sub("a",
          "Compute the ratio r = q/p. "
          "Verify that M(n) = r^{S(n)} is a martingale by computing:\n"
          "  E[r^{X_{n+1}}] = p * r^{+1} + q * r^{-1}\n"
          "and showing it equals 1.")
    p.sub("b",
          "Apply the Optional Stopping Theorem to M(n) = r^{S(n)} "
          "with T = first hitting time of {0, N}. "
          "Let h = P(reach N=6 before 0 | start k=2). Set up and solve:\n"
          "  E[M(T)] = E[M(0)]\n"
          "  r^6 * h + r^0 * (1-h) = r^2\n"
          "Solve for h.")
    p.sub("c",
          "Compare the biased walk result h from (b) to the symmetric walk result\n"
          "h_sym = k/N = 2/6 = 1/3. Is the gambler more or less likely to reach\n"
          "the goal with the biased walk (p=3/5 > 1/2)? Explain intuitively.\n"
          "Also compute P(ruin before goal) = 1 - h.")

    p.sep()

    # ── Q3 ──
    p.Q(3, 35,
        "An asset price evolves as a random multiplicative process: "
        "at each time step the price is multiplied by either u = 1.1 (up) with "
        "probability p or d = 0.9 (down) with probability 1-p. "
        "Starting price is S(0) = 100.")
    p.sub("a",
          "Write S(n) = 100 * u^{A_n} * d^{B_n} where A_n is the number of up "
          "moves and B_n = n - A_n is the number of down moves in n steps. "
          "Under what probability p does E[S(n)] = S(0) for all n? "
          "(This is the 'risk-neutral' probability. Set up E[S(1)] = S(0) and solve.)")
    p.sub("b",
          "Under the risk-neutral probability from (a), show that S(n) is a martingale "
          "by verifying E[S(n+1) | F_n] = S(n). "
          "(Write S(n+1) = S(n) * Y_{n+1} where Y_{n+1} = u with prob p or d with "
          "prob 1-p, and compute E[Y_{n+1}].)")
    p.sub("c",
          "By Jensen's Inequality applied to f(x) = e^x (which is convex), "
          "we have E[e^X] >= e^{E[X]} for any random variable X. "
          "Use this to argue that for p > risk-neutral probability (the real-world "
          "drift is upward), we have E[S(n)] > S(0) under the real-world measure. "
          "Is S(n) then a martingale, supermartingale, or submartingale under the "
          "real-world measure when p > p_risk_neutral?")
    p.save(qp(S, "Question_Set_1.pdf"))


def wald_demoivre_a():
    S = "Walds_Equality_and_De_Moivre_Martingale"
    p = ExamPDF("Wald's Equality and De Moivre's Martingale  -  Answer Key 1")
    p.add_page()

    # ── Q1 ──
    p.AH("Q1  Solution")
    p.AL("a)  E[X_i] and Var[X_i] for a fair die:")
    p.txt("  E[X] = (1+2+3+4+5+6)/6 = 21/6 = 7/2 = 3.5\n\n"
          "  E[X^2] = (1+4+9+16+25+36)/6 = 91/6 ~ 15.167\n\n"
          "  Var[X] = E[X^2] - (E[X])^2 = 91/6 - (7/2)^2\n"
          "         = 91/6 - 49/4\n"
          "         = 182/12 - 147/12\n"
          "         = 35/12 ~ 2.917")

    p.AL("b)  Approximate E[T] via Wald's Equality:")
    p.txt("Wald's Equality: E[S(T)] = E[X] * E[T]\n\n"
          "Since S(T) >= 100 and the overshoot is small relative to 100,\n"
          "we approximate E[S(T)] ~ 100. Therefore:\n\n"
          "  100 ~ E[X] * E[T] = (7/2) * E[T]\n"
          "  E[T] ~ 100 / (7/2) = 200/7 ~ 28.57 rolls\n\n"
          "You need approximately 28-29 die rolls to reach a sum of 100.")

    p.AL("c)  Probability of hitting exactly 100:")
    p.txt("By renewal theory (the renewal process where S(n) is the position and\n"
          "100 is a renewal target), the long-run probability of the sum passing\n"
          "through any specific integer m is approximately 1/E[X] = 2/7.\n\n"
          "  P(S(n) = 100 for some n) ~ 1/E[X] = 2/7 ~ 0.286\n\n"
          "About a 28.6% chance of landing exactly on 100 at some step.\n"
          "The remaining ~71.4% of the time, the sum jumps over 100.\n"
          "(For example, at sum 95 you roll a 6 and land on 101.)")

    p.sep()

    # ── Q2 ──
    p.AH("Q2  Solution")
    p.AL("a)  Verify r = q/p and E[r^{X_{n+1}}] = 1:")
    p.txt("  p = 3/5, q = 2/5, r = q/p = (2/5)/(3/5) = 2/3\n\n"
          "Verify E[r^{X_{n+1}}] = 1:\n"
          "  E[r^{X_{n+1}}] = p * r^{+1} + q * r^{-1}\n"
          "                 = (3/5) * (2/3) + (2/5) * (3/2)\n"
          "                 = 2/5 + 3/5\n"
          "                 = 1  (OK)\n\n"
          "Therefore:\n"
          "  E[M(n+1) | F_n] = M(n) * E[r^{X_{n+1}}] = M(n) * 1 = M(n)\n"
          "M(n) = r^{S(n)} = (2/3)^{S(n)} is a martingale.")

    p.AL("b)  Gambler's Ruin probability h via OST on De Moivre's martingale:")
    p.txt("Apply OST to M(n) = (2/3)^{S(n)} with T = first hit of {0, 6},\n"
          "starting at S(0) = k = 2:\n\n"
          "  E[M(T)] = E[M(0)] = r^k = (2/3)^2 = 4/9\n\n"
          "At stopping time T:\n"
          "  M(T) = r^6 = (2/3)^6 = 64/729  with probability h (reach N=6)\n"
          "  M(T) = r^0 = 1                 with probability 1-h (reach 0)\n\n"
          "Setting up the equation:\n"
          "  (64/729) * h + 1 * (1 - h) = 4/9\n"
          "  (64/729) * h + 1 - h = 4/9\n"
          "  h * (64/729 - 1) = 4/9 - 1\n"
          "  h * (64/729 - 729/729) = 4/9 - 9/9\n"
          "  h * (-665/729) = -5/9\n"
          "  h = (5/9) / (665/729)\n"
          "    = (5/9) * (729/665)\n"
          "    = 5 * 81 / 665\n"
          "    = 405 / 665\n"
          "    = 81/133 ~ 0.609")

    p.AL("c)  Comparison to symmetric walk and P(ruin):")
    p.txt("Symmetric walk (p = 1/2): h_sym = k/N = 2/6 = 1/3 ~ 0.333\n"
          "Biased walk   (p = 3/5): h = 81/133 ~ 0.609\n\n"
          "With upward bias (p = 3/5 > 1/2), the probability of reaching the\n"
          "goal INCREASES significantly: from 33.3% to 60.9%.\n\n"
          "Intuition: with drift +1 on average per step (E[X] = 2p-1 = 0.2 > 0),\n"
          "the walk tends to move toward higher states, making N=6 more reachable\n"
          "than ruin at 0 from position k=2.\n\n"
          "  P(ruin before goal) = 1 - h = 1 - 81/133 = 52/133 ~ 0.391")

    p.sep()

    # ── Q3 ──
    p.AH("Q3  Solution")
    p.AL("a)  Risk-neutral probability p*:")
    p.txt("Write S(1) = S(0) * Y_1 where Y_1 = u=1.1 with prob p or d=0.9 with prob 1-p.\n\n"
          "For S(n) to be a martingale (E[S(1)] = S(0)):\n"
          "  E[S(1)] = S(0) * E[Y_1] = S(0) * (p*u + (1-p)*d) = S(0)\n"
          "  => p*u + (1-p)*d = 1\n"
          "  => p*1.1 + (1-p)*0.9 = 1\n"
          "  => 0.9 + p*(1.1 - 0.9) = 1\n"
          "  => 0.9 + 0.2*p = 1\n"
          "  => p* = 0.1/0.2 = 0.5\n\n"
          "The risk-neutral probability is p* = 1/2 (equal weight to up and down).\n"
          "This makes sense: when p*u + (1-p*)d = 1, the expected return is zero,\n"
          "meaning the asset has no drift under this measure.")

    p.AL("b)  S(n) is a martingale under p* = 1/2:")
    p.txt("Write S(n+1) = S(n) * Y_{n+1} where Y_{n+1} = 1.1 (prob 1/2) or 0.9 (prob 1/2),\n"
          "and Y_{n+1} is independent of F_n.\n\n"
          "  E[S(n+1) | F_n] = S(n) * E[Y_{n+1} | F_n]\n"
          "                  = S(n) * E[Y_{n+1}]  (by independence)\n"
          "                  = S(n) * (0.5*1.1 + 0.5*0.9)\n"
          "                  = S(n) * (0.55 + 0.45)\n"
          "                  = S(n) * 1.0\n"
          "                  = S(n)  (OK)\n\n"
          "So S(n) is indeed a martingale under p* = 1/2.")

    p.AL("c)  Jensen's Inequality and real-world measure:")
    p.txt("Under the real-world measure with p > p* = 1/2 (upward drift):\n\n"
          "  E[Y] = p*1.1 + (1-p)*0.9 = 0.9 + 0.2*p > 0.9 + 0.2*0.5 = 1\n"
          "  (since p > 0.5 implies 0.2*p > 0.1)\n\n"
          "So E[Y] > 1 under the real-world measure with p > 1/2.\n\n"
          "  E[S(n+1) | F_n] = S(n) * E[Y] > S(n)\n\n"
          "=> S(n) is a SUBMARTINGALE under the real-world measure with upward drift.\n\n"
          "Jensen's connection:\n"
          "The multiplicative model S(n) = S(0) * Y_1 * ... * Y_n can be written as\n"
          "S(n) = S(0) * e^{Z_1 + ... + Z_n} where Z_i = log(Y_i). By Jensen's\n"
          "inequality with the convex function f(x) = e^x:\n"
          "  E[S(n)] = S(0)*E[e^{Z_1+...+Z_n}] >= S(0)*e^{E[Z_1+...+Z_n]}\n\n"
          "Since E[Z_i] = p*log(1.1) + (1-p)*log(0.9) > 0 when p > 1/2 (more up\n"
          "moves on average, and log(1.1) > |log(0.9)| is not exactly true but the\n"
          "principle holds for E[Y]>1), the asset price grows on average.\n"
          "This confirms E[S(n)] > S(0) under upward drift, i.e. S(n) is a submartingale.")
    p.save(ap(S, "Question_Set_1_Answers.pdf"))


# ==============================================================================
# MAIN
# ==============================================================================
if __name__ == "__main__":
    print("\n=== Folders 2026-05-21 + 2026-06-04 + last/: Martingales | Wald | De Moivre ===\n")
    print("Generating Question Sets...")
    martin_ost_q()
    wald_demoivre_q()

    print("\nGenerating Answer Keys...")
    martin_ost_a()
    wald_demoivre_a()

    print("\nDone. 4 PDFs created.")
